'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {supabase} from '../../../lib/supabase';
type Game={id:string;played_on:string;kickoff_time:string|null;venue:string|null;match_type:'amistoso'|'campeonato';has_two_frames:boolean;opponents:{name:string}|null;matches:{status:string}[]};
export default function Partidas(){const router=useRouter();const [teamId,setTeamId]=useState(''),[teamName,setTeamName]=useState(''),[games,setGames]=useState<Game[]>([]),[open,setOpen]=useState(false),[opponent,setOpponent]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState(''),[venue,setVenue]=useState(''),[type,setType]=useState<'amistoso'|'campeonato'>('amistoso'),[two,setTwo]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:p}=await supabase.from('profiles').select('role,team_id,teams(name)').eq('user_id',user.id).maybeSingle();if(!p||p.role!=='team_owner'||!p.team_id){router.replace('/login');return}setTeamId(p.team_id);const t=p.teams as unknown as {name?:string}|null;setTeamName(t?.name||'Seu time');const {data,error}=await supabase.from('confrontations').select('id,played_on,kickoff_time,venue,match_type,has_two_frames,opponents(name),matches(status)').eq('team_id',p.team_id).eq('modality','futsal').order('played_on',{ascending:true});if(error)setError(error.message);else setGames((data??[]) as unknown as Game[])}useEffect(()=>{load()},[]);
 const state=(g:Game)=>g.matches.length>0&&g.matches.every(m=>m.status==='finalized')?'finalized':g.matches.some(m=>m.status==='awaiting_sheet'||m.status==='finalized')?'awaiting_sheet':'scheduled';
 async function save(e:FormEvent){e.preventDefault();setError('');if(!teamId||!opponent.trim()||!date)return;setSaving(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sua sessão expirou. Entre novamente.');const res=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/varz10-create-confrontation`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({opponent:opponent.trim(),date,time:time||null,venue:venue.trim()||null,match_type:type,has_two_frames:two})});const body=await res.json();if(!res.ok)throw new Error(body.error||'Não foi possível agendar o confronto.');setOpponent('');setDate('');setTime('');setVenue('');setType('amistoso');setTwo(false);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível agendar o confronto.')}finally{setSaving(false)}}
 return <main className="teamContentPage"><div className="subTop"><Link href="/time">← Início</Link><span>VARZ10 • {teamName}</span></div><section className="contentWrap"><div className="listHead"><div><p className="eyebrow">FUTSAL / QUADRA</p><h1>Partidas</h1><p className="muted">Organize os próximos confrontos e acompanhe os resultados.</p></div><button className="primary" onClick={()=>setOpen(!open)}>+ Novo confronto</button></div>{open&&<form className="playerForm" onSubmit={save}><div className="twoCols"><label>Adversário<input required value={opponent} onChange={e=>setOpponent(e.target.value)} placeholder="Ex: União City"/></label><label>Tipo da partida<select value={type} onChange={e=>setType(e.target.value as 'amistoso'|'campeonato')}><option value="amistoso">Amistoso</option><option value="campeonato">Campeonato</option></select></label><label>Data<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Horário<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>Local<input value={venue} onChange={e=>setVenue(e.target.value)} placeholder="Nome da quadra / endereço"/></label><label className="check"><input type="checkbox" checked={two} onChange={e=>setTwo(e.target.checked)}/> Este confronto terá 2 quadros (1º e 2º Quadro)</label>{error&&<div className="firstAccess"><p>{error}</p></div>}<div className="formActions"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando...':'Agendar confronto'}</button></div></form>}{!open&&error&&<div className="firstAccess"><p>{error}</p></div>}<div className="rosterSummary"><div><span>Próximos</span><strong>{games.filter(g=>state(g)==='scheduled').length}</strong></div><div><span>Aguardando súmula</span><strong>{games.filter(g=>state(g)==='awaiting_sheet').length}</strong></div><div><span>Finalizados</span><strong>{games.filter(g=>state(g)==='finalized').length}</strong></div></div>{games.length===0?<div className="emptyState"><span className="emptyBall">V10</span><h3>Nenhum confronto cadastrado</h3><p>Agende o próximo jogo do seu time.</p></div>:<div className="gameList">{games.map(g=>{const st=state(g);return <article className="gameCard" key={g.id}><div className="gameDate"><strong>{g.played_on.split('-').reverse().slice(0,2).join('/')}</strong><span>{g.kickoff_time?.slice(0,5)||'--:--'}</span></div><div className="gameInfo"><small>{g.match_type==='amistoso'?'AMISTOSO':'CAMPEONATO'} • FUTSAL</small><h3>{teamName} <b>×</b> {g.opponents?.name||'Adversário'}</h3><p>{g.venue||'Local não informado'}{g.has_two_frames?' • 2 quadros':''}</p></div><span className={`statusPill ${st==='finalized'?'active':''}`}>{st==='scheduled'?'Agendado':st==='awaiting_sheet'?'Aguardando súmula':'Finalizado'}</span></article>})}</div>}</section></main>}
