'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '../../lib/supabase';
export default function Login(){
 const [show,setShow]=useState(false),[mode,setMode]=useState<'login'|'first'>('login'),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);const router=useRouter();
 async function normal(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;const res=await fetch(`${url}/functions/v1/varz10-auth`,{method:'POST',headers:{'Content-Type':'application/json','apikey':key!},body:JSON.stringify({login,password})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Não foi possível entrar.');const {error:s}=await supabase.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});if(s)throw s;router.replace(data.user?.role==='super_admin'?'/admin':'/time');router.refresh()}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar.')}finally{setLoading(false)}}
 async function first(e:FormEvent){e.preventDefault();setError('');if(password.length<6){setError('A senha precisa ter pelo menos 6 caracteres.');return}if(password!==confirm){setError('As senhas não conferem.');return}setLoading(true);try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;const res=await fetch(`${url}/functions/v1/varz10-first-access`,{method:'POST',headers:{'Content-Type':'application/json','apikey':key!},body:JSON.stringify({action:'claim',login,code,password})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Não foi possível concluir o primeiro acesso.');const {error:s}=await supabase.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});if(s)throw s;router.replace('/time');router.refresh()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.')}finally{setLoading(false)}}
 return <main className="loginPage"><section className="loginCard"><Link href="/" className="brand center"><span className="loginLogo"><span className="loginCrown">♛</span><strong>VARZ<span>10</span></strong><small>FUTEBOL DE VÁRZEA. SEM LIMITES.</small></span></Link><div className="loginHead"><p className="eyebrow">{mode==='login'?'BEM-VINDO':'PRIMEIRO ACESSO'}</p><h1>{mode==='login'?'Entre na sua conta':'Crie sua senha'}</h1><p>{mode==='login'?'Acesse a gestão do seu time.':'Use o login e o código temporário fornecidos pelo administrador.'}</p></div>{mode==='login'?<form onSubmit={normal}><label>Login<input required value={login} onChange={e=>setLogin(e.target.value)} placeholder="Ex: aliadosdaparma" autoComplete="username"/></label><label>Senha<div className="password"><input required value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} placeholder="Sua senha" autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)}>{show?'Ocultar':'Mostrar'}</button></div></label>{error&&<div className="firstAccess"><p>{error}</p></div>}<button className="primary full" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form>:<form onSubmit={first}><label>Login do time<input required value={login} onChange={e=>setLogin(e.target.value)} placeholder="aliadosdaparma"/></label><label>Código temporário<input required inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label><label>Crie sua senha<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirme sua senha<input required minLength={6} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{error&&<div className="firstAccess"><p>{error}</p></div>}<button className="primary full" disabled={loading}>{loading?'Criando acesso...':'Criar senha e entrar'}</button></form>}<div className="loginHelp"><button type="button" onClick={()=>{setMode(mode==='login'?'first':'login');setError('');setPassword('');setConfirm('')}}>{mode==='login'?'Primeiro acesso?':'Já tenho senha'}</button><p>{mode==='login'?'Recebeu um código do administrador? Clique acima para criar sua senha.':'Voltar para o login normal.'}</p></div><small>Problemas com o acesso? Fale com o administrador VARZ10.</small></section></main>
}